[package]
name = "ckb-discovery"
version = "0.30.1-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p2p = { version = "0.3.0-alpha.1", package = "tentacle", features = ["molc"] }
ckb-logger = { path = "../../util/logger" }
futures = { version = "0.3.0" }
tokio = { version = "0.2.0", features = ["time", "io-util", "tcp", "dns", "stream"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
rand = "0.6.1"
ckb-types = { path = "../../util/types" }
